### ISSUE TITLE
Dynamically changing url appends rather than replacing

### ISSUE THREAD

**Issue by blairjo** [parrisvarney/ng-pdf-viewer#2]
Hi,

If the value of the url property changes , the new pdf is being appended to the bottom of the canvas rather than replacing the previous pdf.

I think all it needs is something like this to clear the element before the initial call to getPages():

```
while (element[0].firstChild) {
  element[0].removeChild(element[0].firstChild);
}
getPages(1, pdf.numPages); 
```

**Comment by parrisvarney** [comment]
Thanks for reporting this.  If you don't mind submitting a pull request I would gladly review and merge it in.

**Comment by blairjo** [comment]
no worries. Have submitted a PR now..

**Comment by parrisvarney** [comment]
Thanks for the PR!  I've verified the changes and merged it in.

**Comment by blairjo** [comment]
:)
